// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notification

import (
	"context"

	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewSMSSenderServiceInterfaceMock creates a new instance of SMSSenderServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSMSSenderServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SMSSenderServiceInterfaceMock {
	mock := &SMSSenderServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SMSSenderServiceInterfaceMock is an autogenerated mock type for the SMSSenderServiceInterface type
type SMSSenderServiceInterfaceMock struct {
	mock.Mock
}

type SMSSenderServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SMSSenderServiceInterfaceMock) EXPECT() *SMSSenderServiceInterfaceMock_Expecter {
	return &SMSSenderServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// SendSMS provides a mock function for the type SMSSenderServiceInterfaceMock
func (_mock *SMSSenderServiceInterfaceMock) SendSMS(ctx context.Context, senderID string, recipient string, body string) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, senderID, recipient, body)

	if len(ret) == 0 {
		panic("no return value specified for SendSMS")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, senderID, recipient, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// SMSSenderServiceInterfaceMock_SendSMS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSMS'
type SMSSenderServiceInterfaceMock_SendSMS_Call struct {
	*mock.Call
}

// SendSMS is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID string
//   - recipient string
//   - body string
func (_e *SMSSenderServiceInterfaceMock_Expecter) SendSMS(ctx interface{}, senderID interface{}, recipient interface{}, body interface{}) *SMSSenderServiceInterfaceMock_SendSMS_Call {
	return &SMSSenderServiceInterfaceMock_SendSMS_Call{Call: _e.mock.On("SendSMS", ctx, senderID, recipient, body)}
}

func (_c *SMSSenderServiceInterfaceMock_SendSMS_Call) Run(run func(ctx context.Context, senderID string, recipient string, body string)) *SMSSenderServiceInterfaceMock_SendSMS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SMSSenderServiceInterfaceMock_SendSMS_Call) Return(serviceError *serviceerror.ServiceError) *SMSSenderServiceInterfaceMock_SendSMS_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *SMSSenderServiceInterfaceMock_SendSMS_Call) RunAndReturn(run func(ctx context.Context, senderID string, recipient string, body string) *serviceerror.ServiceError) *SMSSenderServiceInterfaceMock_SendSMS_Call {
	_c.Call.Return(run)
	return _c
}
